apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-order-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-order-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-order-service
    spec:
      containers:
        - name: order-service
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: PSQL_DB_HOST
              value: {{ .Values.global.postgresql.host }}
            - name: PSQL_DB_PORT
              value: "{{ .Values.global.postgresql.port }}"
            - name: PSQL_DB_USER
              value: {{ .Values.global.postgresql.auth.username }}
            - name: PSQL_DB_PASSWORD
              value: {{ .Values.global.postgresql.auth.password }}
            - name: PSQL_DB_NAME
              value: {{ .Values.global.postgresql.auth.database }}
